FROM python:3.12.0-bookworm

WORKDIR /app

COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt

COPY . .
COPY --from=pokeapi-frontend /app/app/static/build ./app/static/build

RUN mkdir logs database cache app/static/storage -p

CMD ["gunicorn", "-c", "gunicorn_config.py", "app:app"]
