FROM python:3.12.0-bookworm

WORKDIR /app

COPY . .

RUN python -m pip install --no-cache-dir poetry

RUN poetry config virtualenvs.in-project true \
    && poetry install --without dev,test --no-interaction --no-ansi

COPY --from=pokeapi-frontend /app/app/static/build ./app/static/build

RUN mkdir logs database cache app/static/storage -p

CMD /app/.venv/bin/gunicorn -c gunicorn_config.py app:app
