app/static/build/*
app/static/storage/*
app/src

**/*node_modules
**/*__pycache__

**.git
.idea
.editorconfig
**.gitignore
**.gitattributes
.env*

*.config.js
.babelrc
package.json
package-lock.json

Dockerfile
docker-compose.yml
docker
Makefile

LICENSE
README.md

database

cache

logs

geckodriver
