version: '3.8'
services:
    app:
        image: danil7/pokeapi
        container_name: pokeapi-app
        restart: unless-stopped
        env_file:
            - .env.production
        depends_on:
            - db
            - cache
            - ftpd
        volumes:
            - public-app-data:/app/app/static/storage
            - cache-app-data:/app/database
            - db-app-data:/app/cache
            - logs-app-data:/app/logs
        networks:
            - db-conn
            - cache-conn
            - ftpd-conn
        ports:
            - 80:80

    db:
        image: postgres:16.0
        container_name: pokeapi-db
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_DATABASE}
            - PGDATA="/var/lib/postgresql/data/pgdata"
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - db-conn

    cache:
        image: redis:7.0.9-alpine
        container_name: pokeapi-cache
        restart: unless-stopped
        command: redis-server --port "${CACHE_REDIS_PORT}"
        volumes:
            - cache-data:/data
        networks:
            - cache-conn

    ftpd:
        image: stilliard/pure-ftpd:latest
        container_name: pokeapi-ftpd
        restart: unless-stopped
        environment:
            - FTP_USER_NAME=${FTP_USER}
            - FTP_USER_PASS=${FTP_PASSWORD}
            - FTP_USER_HOME=/home/${FTP_USER}/ftp-storage
        volumes:
            - ftpd-data:/home/${FTP_USER}/ftp-storage
        networks:
            - ftpd-conn

volumes:
    db-data:
    cache-data:
    ftpd-data:
    public-app-data:
    cache-app-data:
    db-app-data:
    logs-app-data:

networks:
    db-conn:
        driver: bridge
    cache-conn:
        driver: bridge
    ftpd-conn:
        driver: bridge
