FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache brotli

COPY package.json package-lock.json  ./

RUN npm install

COPY webpack.config.js tailwind.config.js postcss.config.js ./
COPY ./app/templates ./app/templates
COPY ./app/src ./app/src
RUN npm run build

RUN find ./app/static/build -type f \
        \( -name "*.js" -o -name "*.css" -o -name "*.ico" -o -name "*.svg" \) \
        -exec brotli -f -k -Z {} +
